version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8888:80
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/post-series
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test

  cli:
    image: wordpress:cli
    user: xfs
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg
    depends_on:
      - mysql
      - wordpress

volumes:
  wordpress: